In [56]:
import pandas as pd
import plotly.express as px
import ipywidgets as widgets
from IPython.display import display

# Data Import: Load Excel file into DataFrame
file_path = "09_Outputs/main_data.xlsx"
df_main = pd.read_excel(file_path)

# Fixed reference columns
fixed_columns = ['Entity', 'Year', 'Code']

# List of columns to visualize (excluding the fixed columns)
columns_to_visualize = [col for col in df_main.columns if col not in fixed_columns]

# Function to create interactive choropleth map
def plot_choropleth(selected_column):
    # Filter the DataFrame to only include rows where the selected column has non-NaN values
    df_filtered = df_main[df_main[selected_column].notna()]
    
    # Determine the last available year for the selected column
    last_valid_year = df_filtered['Year'].max()
    
    # Create the choropleth map
    fig = px.choropleth(df_filtered,
                        locations='Code', 
                        color=selected_column,
                        hover_name='Entity',
                        animation_frame='Year',
                        title=f"Choropleth of {selected_column}",
                        color_continuous_scale=px.colors.sequential.Plasma)
    
    # Set the size of the map
    fig.update_layout(autosize=False, width=1000, height=600)
    
    # Set the initial frame to the last available year for the selected column
    fig.layout.sliders[0].active = df_filtered['Year'].nunique() - 1
    
    fig.show()

# Dropdown menu: Column selection for visualization
dropdown = widgets.Dropdown(options=columns_to_visualize, description='Select Column:', value=columns_to_visualize[0])

# Interactive visualization
interactive_plot = widgets.interactive(plot_choropleth, selected_column=dropdown)
display(interactive_plot)

interactive(children=(Dropdown(description='Select Column:', options=('Annual CO₂ emissions', 'Renewables (TWh…

In [32]:
df_main_2 = df_main.iloc[:6, :4]
df_main_2

          Entity  Year Code  Annual CO₂ emissions
0  "Afghanistan"  1965  AFG             1006917.0
1  "Afghanistan"  1966  AFG             1091159.0
2  "Afghanistan"  1967  AFG             1281865.0
3  "Afghanistan"  1968  AFG             1223391.0
4  "Afghanistan"  1969  AFG              941232.0
5  "Afghanistan"  1970  AFG             1670397.0

In [33]:
import pandas as pd
import plotly.express as px
import dash
import dash_core_components as dcc
import dash_html_components as html

# Load the data into a DataFrame
df_main_2 = pd.DataFrame({
    'Entity': ['Afghanistan', 'Afghanistan', 'Afghanistan', 'Afghanistan', 'Afghanistan', 'Afghanistan'],
    'Year': [1965, 1966, 1967, 1968, 1969, 1970],
    'Code': ['AFG', 'AFG', 'AFG', 'AFG', 'AFG', 'AFG'],
    'Annual CO2 emissions': [1006917.0, 1091159.0, 1281865.0, 1223391.0, 941232.0, 1670397.0]
})

# Create the choropleth map
fig = px.choropleth(df_main_2, locations='Code', color='Annual CO2 emissions', animation_frame='Year',
                    color_continuous_scale=px.colors.sequential.Plasma)

# Create the Dash app
app = dash.Dash(__name__)

# Define the layout of the app
app.layout = html.Div([
    dcc.Graph(
        id='choropleth_map',
        figure=fig
    ),
    dcc.Slider(
        id='year_slider',
        min=df_main_2['Year'].min(),
        max=df_main_2['Year'].max(),
        value=df_main_2['Year'].max(),
        marks={str(year): str(year) for year in df_main_2['Year'].unique()},
        step=None,
        updatemode='drag'
    )
])

# Define the callback function for the slider
@app.callback(
    dash.dependencies.Output('choropleth_map', 'figure'),
    [dash.dependencies.Input('year_slider', 'value')]
)
def update_choropleth_map(year):
    filtered_df = df_main_2[df_main_2['Year'] == year]
    fig = px.choropleth(filtered_df, locations='Code', color='Annual CO2 emissions',
                        color_continuous_scale=px.colors.sequential.Plasma)
    return fig

# Run the app
if __name__ == '__main__':
    app.run_server(debug=True)

C:\Users\Alpha\AppData\Local\Temp\ipykernel_47036\2848326372.py:4: UserWarning:


The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`

C:\Users\Alpha\AppData\Local\Temp\ipykernel_47036\2848326372.py:5: UserWarning:


The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`

In [35]:
import pandas as pd
import plotly.express as px
import ipywidgets as widgets
from IPython.display import display

# Data Import: Load Excel file into DataFrame
file_path = "09_Outputs/main_data.xlsx"
df_main = pd.read_excel(file_path)

# Fixed reference columns
fixed_columns = ['Entity', 'Year', 'Code']

# List of columns to visualize (excluding the fixed columns)
columns_to_visualize = [col for col in df_main.columns if col not in fixed_columns]

# Initialize an empty DataFrame to store the start and end dates for each column
date_dataframe = pd.DataFrame(columns=['Column_Name', 'Start_Year', 'End_Year'])

# Loop through each column in df_main, excluding the fixed_columns
for col in columns_to_visualize:
    # Filter the DataFrame to only include rows where the selected column has non-NaN values
    df_filtered = df_main[df_main[col].notna()]
    
    # Get the min and max year for the filtered DataFrame
    min_year = df_filtered['Year'].min()
    max_year = df_filtered['Year'].max()
    
    # Append the information to date_dataframe
    date_dataframe = date_dataframe.append({'Column_Name': col, 'Start_Year': min_year, 'End_Year': max_year}, ignore_index=True)

# Function to create interactive choropleth map
def plot_choropleth(selected_column):
    # Filter the DataFrame to only include rows where the selected column has non-NaN values
    df_filtered = df_main[df_main[selected_column].notna()]
    
    # Determine the last available year for the selected column
    last_valid_year = df_filtered['Year'].max()
    
    # Create the choropleth map
    fig = px.choropleth(df_filtered,
                        locations='Code', 
                        color=selected_column,
                        hover_name='Entity',
                        animation_frame='Year',
                        title=f"Choropleth of {selected_column}",
                        color_continuous_scale=px.colors.sequential.Plasma)
    
    # Set the size of the map
    fig.update_layout(autosize=False, width=1000, height=600)
    
    # Set the initial frame to the last available year for the selected column
    fig.layout.sliders[0].active = df_filtered['Year'].nunique() - 1
    
    fig.show()

# Dropdown menu: Column selection for visualization
dropdown = widgets.Dropdown(options=columns_to_visualize, description='Select Column:', value=columns_to_visualize[0])

# Interactive visualization
interactive_plot = widgets.interactive(plot_choropleth, selected_column=dropdown)
display(interactive_plot)

C:\Users\Alpha\AppData\Local\Temp\ipykernel_47036\2164392679.py:29: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Alpha\AppData\Local\Temp\ipykernel_47036\2164392679.py:29: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Alpha\AppData\Local\Temp\ipykernel_47036\2164392679.py:29: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Alpha\AppData\Local\Temp\ipykernel_47036\2164392679.py:29: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Alpha\AppData\Local\Temp\ipykernel_47036\2164392679.py:29: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Alpha\AppData\Local\Temp\ipykernel_47036\2164392679.py:29: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Alpha\AppData\Local\Temp\ipykernel_47036\2164392679.py:29: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Alpha\AppData\Local\Temp\ipykernel_47036\2164392679.py:29: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Alpha\AppData\Local\Temp\ipykernel_47036\2164392679.py:29: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Alpha\AppData\Local\Temp\ipykernel_47036\2164392679.py:29: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Alpha\AppData\Local\Temp\ipykernel_47036\2164392679.py:29: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Alpha\AppData\Local\Temp\ipykernel_47036\2164392679.py:29: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Alpha\AppData\Local\Temp\ipykernel_47036\2164392679.py:29: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Alpha\AppData\Local\Temp\ipykernel_47036\2164392679.py:29: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Alpha\AppData\Local\Temp\ipykernel_47036\2164392679.py:29: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Alpha\AppData\Local\Temp\ipykernel_47036\2164392679.py:29: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Alpha\AppData\Local\Temp\ipykernel_47036\2164392679.py:29: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Alpha\AppData\Local\Temp\ipykernel_47036\2164392679.py:29: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Alpha\AppData\Local\Temp\ipykernel_47036\2164392679.py:29: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

interactive(children=(Dropdown(description='Select Column:', options=('Annual CO₂ emissions', 'Renewables (TWh…

In [37]:
date_dataframe

                                          Column_Name Start_Year End_Year
0                                Annual CO₂ emissions       1965     2021
1                Renewables (TWh growth - equivalent)       1966     2022
2                   Annual CO₂ emissions from flaring       1965     2021
3                       Annual CO₂ emissions from gas       1965     2021
4                       Annual CO₂ emissions from oil       1965     2021
5                      Annual CO₂ emissions from coal       1965     2021
6                    Primary energy consumption (TWh)       1965     2022
7   Change in global mean surface temperature caus...       1965     2021
8   Annual greenhouse gas emissions in CO2 equival...       1965     2021
9                 Electricity from fossil fuels (TWh)       1985     2022
10         Other renewables excluding bioenergy (TWh)       1965     2022
11                              Oil consumption - TWh       1965     2022
12         Primary energy consumption per GDP (kWh/$)       1965     2018
13                       Low-carbon electricity (TWh)       1965     2022
14                            GDP (constant 2015 US$)       1965     2021
15  Renewable electricity (% electricity productio...       1990     2014
16                        Solar photovoltaic capacity       2000     2022
17  Annual greenhouse gas emissions in CO2 equival...       1965     2021
18                        Electricity from wind (TWh)       1965     2022

In [39]:
import pandas as pd
import plotly.express as px
import ipywidgets as widgets
from IPython.display import display

# Data Import: Load Excel file into DataFrame
file_path = "09_Outputs/main_data.xlsx"
df_main = pd.read_excel(file_path)

# Remove continents to create choro_df (customize this list as needed)
continents = ['Africa', 'Asia', 'Europe', 'North America', 'Oceania', 'South America', 'Antarctica']
choro_df = df_main[~df_main['Entity'].isin(continents)]

# Fixed reference columns
fixed_columns = ['Entity', 'Year', 'Code']

# List of columns to visualize (excluding the fixed columns)
columns_to_visualize = [col for col in choro_df.columns if col not in fixed_columns]

# Initialize an empty DataFrame to store the start and end dates for each column
date_dataframe_list = []

# Loop through each column in df_main, excluding the fixed_columns
for col in columns_to_visualize:
    df_filtered = choro_df[choro_df[col].notna()]
    min_year = df_filtered['Year'].min()
    max_year = df_filtered['Year'].max()
    date_dataframe_list.append({'Column_Name': col, 'Start_Year': min_year, 'End_Year': max_year})

# Create the date_dataframe using pd.DataFrame
date_dataframe = pd.DataFrame(date_dataframe_list)

# Function to create interactive choropleth map
def plot_choropleth(selected_column):
    df_filtered = choro_df[choro_df[selected_column].notna()]
    last_valid_year = df_filtered['Year'].max()
    fig = px.choropleth(df_filtered,
                        locations='Code',
                        color=selected_column,
                        hover_name='Entity',
                        animation_frame='Year',
                        title=f"Choropleth of {selected_column}",
                        color_continuous_scale=px.colors.sequential.Plasma)
    fig.update_layout(autosize=False, width=1000, height=600)
    fig.layout.sliders[0].active = df_filtered['Year'].nunique() - 1
    fig.show()

# Dropdown menu: Column selection for visualization
dropdown = widgets.Dropdown(options=columns_to_visualize, description='Select Column:', value=columns_to_visualize[0])

# Interactive visualization
interactive_plot = widgets.interactive(plot_choropleth, selected_column=dropdown)
display(interactive_plot)

interactive(children=(Dropdown(description='Select Column:', options=('Annual CO₂ emissions', 'Renewables (TWh…

In [62]:
import pandas as pd
import plotly.express as px
import ipywidgets as widgets
from IPython.display import display

# Data Import: Load Excel file into DataFrame
file_path = "09_Outputs/main_data.xlsx"
df_main = pd.read_excel(file_path)

# Remove quotation marks from the 'Entity' column
df_main['Entity'] = df_main['Entity'].str.replace('"', '')

# Remove continents and 'World' to create choro_df (customize this list as needed)
continents_and_world = ['Africa', 'Asia', 'Europe', 'North America', 'Oceania', 'South America', 'Antarctica', 'World']
choro_df = df_main[~df_main['Entity'].isin(continents_and_world)]


# Fixed reference columns
fixed_columns = ['Entity', 'Year', 'Code']

# List of columns to visualize (excluding the fixed columns)
columns_to_visualize = [col for col in choro_df.columns if col not in fixed_columns]

# Function to create interactive choropleth map
def plot_choropleth(selected_column):
    df_filtered = choro_df[choro_df[selected_column].notna()]
    last_valid_year = df_filtered['Year'].max()
    
    # Get Top-5 countries for the last available year
    df_top5 = df_filtered[df_filtered['Year'] == last_valid_year]
    df_top5 = df_top5.nlargest(5, selected_column)
    
    print(f"Top 5 countries in {last_valid_year} for {selected_column}:")
    print(df_top5[['Entity', selected_column]])
    
    fig = px.choropleth(df_filtered,
                        locations='Code',
                        color=selected_column,
                        hover_name='Entity',
                        animation_frame='Year',
                        title=f"Choropleth of {selected_column}",
                        color_continuous_scale=px.colors.sequential.Plasma)
    fig.update_layout(autosize=False, width=1000, height=600)
    fig.layout.sliders[0].active = df_filtered['Year'].nunique() - 1
    fig.show()

# Dropdown menu: Column selection for visualization
dropdown = widgets.Dropdown(options=columns_to_visualize, description='Select Column:', value=columns_to_visualize[0])

# Interactive visualization
interactive_plot = widgets.interactive(plot_choropleth, selected_column=dropdown)
display(interactive_plot)

interactive(children=(Dropdown(description='Select Column:', options=('Annual CO₂ emissions', 'Renewables (TWh…

In [44]:
df_main

,Entity,Year,Code,Annual CO₂ emissions,Renewables (TWh growth - equivalent),Annual CO₂ emissions from flaring,Annual CO₂ emissions from gas,Annual CO₂ emissions from oil,Annual CO₂ emissions from coal,Primary energy consumption (TWh),...,Electricity from fossil fuels (TWh),Other renewables excluding bioenergy (TWh),Oil consumption - TWh,Primary energy consumption per GDP (kWh/$),Low-carbon electricity (TWh),GDP (constant 2015 US$),Renewable electricity (% electricity production) (World Bank (2015)),Solar photovoltaic capacity,Annual greenhouse gas emissions in CO2 equivalents,Electricity from wind (TWh)
0,Afghanistan,1965,AFG,1006917.0,NaN,0.0,0.0,542272.0,381056.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24430504.0,NaN
1,Afghanistan,1966,AFG,1091159.0,NaN,0.0,0.0,575248.0,428688.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25174948.0,NaN
2,Afghanistan,1967,AFG,1281865.0,NaN,0.0,260144.0,556928.0,399376.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24644464.0,NaN
3,Afghanistan,1968,AFG,1223391.0,NaN,0.0,347041.0,496817.0,332429.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24382198.0,NaN
4,Afghanistan,1969,AFG,941232.0,NaN,0.0,0.0,527616.0,362736.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23233260.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11721,Zimbabwe,2018,ZWE,11795478.0,NaN,0.0,0.0,4059712.0,7177776.0,51.809430,...,3.73,0.0,NaN,2.280811,5.46,2.201518e+10,NaN,0.008564,39079344.0,0.0
11722,Zimbabwe,2019,ZWE,11114607.0,NaN,0.0,0.0,3656672.0,6888320.0,46.119940,...,3.66,0.0,NaN,NaN,4.58,2.062108e+10,NaN,0.011827,38701416.0,0.0
11723,Zimbabwe,2020,ZWE,10607897.0,NaN,0.0,0.0,3316712.0,6721571.0,41.996760,...,3.40,0.0,NaN,NaN,4.19,1.900914e+10,NaN,0.014070,37733230.0,0.0
11724,Zimbabwe,2021,ZWE,11296114.0,NaN,0.0,0.0,3500879.0,7225620.0,42.145393,...,3.61,0.0,NaN,NaN,4.42,2.061884e+10,NaN,0.027941,38060010.0,0.0
11725,Zimbabwe,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.041249,NaN,NaN

In [61]:
def plot_choropleth(selected_column):
    df_filtered = choro_df[choro_df[selected_column].notna()]
    last_valid_year = df_filtered['Year'].max()
    
    # Get Top-5 countries for the last available year
    df_top5 = df_filtered[df_filtered['Year'] == last_valid_year]
    df_top5 = df_top5.nlargest(5, selected_column)
    
    print(f"Top 5 countries in {last_valid_year} for {selected_column}:")
    print(df_top5[['Entity', selected_column]])
    
    fig = px.choropleth(df_filtered.sort_values(by='Year', ascending=False),  # Sort data by Year in descending order
                        locations='Code',
                        color=selected_column,
                        hover_name='Entity',
                        animation_frame='Year',
                        title=f"Choropleth of {selected_column}",
                        color_continuous_scale=px.colors.sequential.Plasma)
    
    fig.update_layout(autosize=False, width=1000, height=600)
    fig.show()

# Dropdown menu: Column selection for visualization
dropdown = widgets.Dropdown(options=columns_to_visualize, description='Select Column:', value=columns_to_visualize[0])

# Interactive visualization
interactive_plot = widgets.interactive(plot_choropleth, selected_column=dropdown)
display(interactive_plot)

interactive(children=(Dropdown(description='Select Column:', options=('Annual CO₂ emissions', 'Renewables (TWh…

In [50]:
##################  DONT CHANGE!!!!!!!!!!!!!!!!! ######

In [64]:
import pandas as pd
import plotly.express as px
import ipywidgets as widgets
from IPython.display import display

# Data Import: Load Excel file into DataFrame
file_path = "09_Outputs/main_data.xlsx"
df_main = pd.read_excel(file_path)

# Remove quotation marks from the 'Entity' column
df_main['Entity'] = df_main['Entity'].str.replace('"', '')

# Remove continents and 'World' to create choro_df (customize this list as needed)
continents_and_world = ['Africa', 'Asia', 'Europe', 'North America', 'Oceania', 'South America', 'Antarctica', 'World']
choro_df = df_main[~df_main['Entity'].isin(continents_and_world)]


# Fixed reference columns
fixed_columns = ['Entity', 'Year', 'Code']

# List of columns to visualize (excluding the fixed columns)
columns_to_visualize = [col for col in choro_df.columns if col not in fixed_columns]

# Function to create interactive choropleth map
def plot_choropleth(selected_column):
    df_filtered = choro_df[choro_df[selected_column].notna()]
    last_valid_year = df_filtered['Year'].max()
    
    # Get Top-5 countries for the last available year
    df_top5 = df_filtered[df_filtered['Year'] == last_valid_year]
    df_top5 = df_top5.nlargest(5, selected_column)
    
    print(f"Top 5 countries in {last_valid_year} for {selected_column}:")
    print(df_top5[['Entity', selected_column]])
    
    fig = px.choropleth(df_filtered.sort_values(by='Year', ascending=False),  # Sort data by Year in descending order
                        locations='Code',
                        color=selected_column,
                        hover_name='Entity',
                        animation_frame='Year',
                        title=f"Choropleth of {selected_column}",
                        color_continuous_scale=px.colors.sequential.Plasma)
    
    fig.update_layout(autosize=False, width=1000, height=600)
    fig.show()

# Dropdown menu: Column selection for visualization
dropdown = widgets.Dropdown(options=columns_to_visualize, description='Select Column:', value=columns_to_visualize[0])

# Interactive visualization
interactive_plot = widgets.interactive(plot_choropleth, selected_column=dropdown)
display(interactive_plot)

interactive(children=(Dropdown(description='Select Column:', options=('Annual CO₂ emissions', 'Renewables (TWh…